//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "food_reactions"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub realm_id: Uuid,
    pub device_id: String,
    pub user_id: Uuid,
    pub analysis_item_id: Option<Uuid>,
    pub eaten_at: DateTimeWithTimeZone,
    pub feeling: String,
    pub symptom_onset: String,
    pub notes: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Uuid,
    pub updated_by: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    RealmId,
    DeviceId,
    UserId,
    AnalysisItemId,
    EatenAt,
    Feeling,
    SymptomOnset,
    Notes,
    CreatedAt,
    UpdatedAt,
    CreatedBy,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FoodAnalysisItems,
    FoodReactionSymptoms,
    Realms,
    Users3,
    Users2,
    Users1,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::DeviceId => ColumnType::Text.def(),
            Self::UserId => ColumnType::Uuid.def(),
            Self::AnalysisItemId => ColumnType::Uuid.def().null(),
            Self::EatenAt => ColumnType::TimestampWithTimeZone.def(),
            Self::Feeling => ColumnType::Text.def(),
            Self::SymptomOnset => ColumnType::Text.def(),
            Self::Notes => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::CreatedBy => ColumnType::Uuid.def(),
            Self::UpdatedBy => ColumnType::Uuid.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FoodAnalysisItems => Entity::belongs_to(super::food_analysis_items::Entity)
                .from(Column::AnalysisItemId)
                .to(super::food_analysis_items::Column::Id)
                .into(),
            Self::FoodReactionSymptoms => {
                Entity::has_many(super::food_reaction_symptoms::Entity).into()
            }
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
            Self::Users3 => Entity::belongs_to(super::users::Entity)
                .from(Column::CreatedBy)
                .to(super::users::Column::Id)
                .into(),
            Self::Users2 => Entity::belongs_to(super::users::Entity)
                .from(Column::UpdatedBy)
                .to(super::users::Column::Id)
                .into(),
            Self::Users1 => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::food_analysis_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FoodAnalysisItems.def()
    }
}

impl Related<super::food_reaction_symptoms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FoodReactionSymptoms.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
