//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "food_analysis_items"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub realm_id: Uuid,
    pub request_id: Uuid,
    pub result_id: Uuid,
    pub dish_index: i32,
    pub input_index: Option<i32>,
    pub dish_name: String,
    pub safety_level: String,
    pub risk_score: i32,
    pub risk_band: String,
    pub summary_reason: String,
    pub ibd_concerns: Vec<String>,
    pub ibs_concerns: Vec<String>,
    pub recommendations: String,
    pub image_object_key: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Uuid,
    pub updated_by: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    RealmId,
    RequestId,
    ResultId,
    DishIndex,
    InputIndex,
    DishName,
    SafetyLevel,
    RiskScore,
    RiskBand,
    SummaryReason,
    IbdConcerns,
    IbsConcerns,
    Recommendations,
    ImageObjectKey,
    CreatedAt,
    UpdatedAt,
    CreatedBy,
    UpdatedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FoodAnalysisRequests,
    FoodAnalysisResults,
    FoodAnalysisTriggers,
    FoodReactions,
    Realms,
    Users2,
    Users1,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::RequestId => ColumnType::Uuid.def(),
            Self::ResultId => ColumnType::Uuid.def(),
            Self::DishIndex => ColumnType::Integer.def(),
            Self::InputIndex => ColumnType::Integer.def().null(),
            Self::DishName => ColumnType::Text.def(),
            Self::SafetyLevel => ColumnType::Text.def(),
            Self::RiskScore => ColumnType::Integer.def(),
            Self::RiskBand => ColumnType::Text.def(),
            Self::SummaryReason => ColumnType::Text.def(),
            Self::IbdConcerns => ColumnType::Array(RcOrArc::new(ColumnType::Text)).def(),
            Self::IbsConcerns => ColumnType::Array(RcOrArc::new(ColumnType::Text)).def(),
            Self::Recommendations => ColumnType::Text.def(),
            Self::ImageObjectKey => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::CreatedBy => ColumnType::Uuid.def(),
            Self::UpdatedBy => ColumnType::Uuid.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FoodAnalysisRequests => Entity::belongs_to(super::food_analysis_requests::Entity)
                .from(Column::RequestId)
                .to(super::food_analysis_requests::Column::Id)
                .into(),
            Self::FoodAnalysisResults => Entity::belongs_to(super::food_analysis_results::Entity)
                .from(Column::ResultId)
                .to(super::food_analysis_results::Column::Id)
                .into(),
            Self::FoodAnalysisTriggers => {
                Entity::has_many(super::food_analysis_triggers::Entity).into()
            }
            Self::FoodReactions => Entity::has_many(super::food_reactions::Entity).into(),
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
            Self::Users2 => Entity::belongs_to(super::users::Entity)
                .from(Column::CreatedBy)
                .to(super::users::Column::Id)
                .into(),
            Self::Users1 => Entity::belongs_to(super::users::Entity)
                .from(Column::UpdatedBy)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::food_analysis_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FoodAnalysisRequests.def()
    }
}

impl Related<super::food_analysis_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FoodAnalysisResults.def()
    }
}

impl Related<super::food_analysis_triggers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FoodAnalysisTriggers.def()
    }
}

impl Related<super::food_reactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FoodReactions.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
