//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub mod prelude;

pub mod auth_sessions;
pub mod clients;
pub mod credentials;
pub mod device_profiles;
pub mod food_analysis_items;
pub mod food_analysis_requests;
pub mod food_analysis_results;
pub mod food_analysis_triggers;
pub mod food_reaction_symptoms;
pub mod food_reactions;
pub mod jwt_keys;
pub mod prompts;
pub mod realm_settings;
pub mod realms;
pub mod redirect_uris;
pub mod refresh_tokens;
pub mod roles;
pub mod security_events;
pub mod stored_objects;
pub mod user_required_actions;
pub mod user_role;
pub mod user_sessions;
pub mod users;
pub mod webhook_subscribers;
pub mod webhooks;
