//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "prompts"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub realm_id: Uuid,
    pub name: String,
    pub description: String,
    pub template: String,
    pub version: String,
    pub is_active: bool,
    pub is_deleted: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    pub created_by: Uuid,
    pub updated_by: Uuid,
    pub deleted_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    RealmId,
    Name,
    Description,
    Template,
    Version,
    IsActive,
    IsDeleted,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
    CreatedBy,
    UpdatedBy,
    DeletedBy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FoodAnalysisRequests,
    Realms,
    Users3,
    Users2,
    Users1,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Description => ColumnType::Text.def(),
            Self::Template => ColumnType::Text.def(),
            Self::Version => ColumnType::String(StringLen::N(50u32)).def(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::IsDeleted => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::DeletedAt => ColumnType::DateTime.def().null(),
            Self::CreatedBy => ColumnType::Uuid.def(),
            Self::UpdatedBy => ColumnType::Uuid.def(),
            Self::DeletedBy => ColumnType::Uuid.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FoodAnalysisRequests => {
                Entity::has_many(super::food_analysis_requests::Entity).into()
            }
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
            Self::Users3 => Entity::belongs_to(super::users::Entity)
                .from(Column::CreatedBy)
                .to(super::users::Column::Id)
                .into(),
            Self::Users2 => Entity::belongs_to(super::users::Entity)
                .from(Column::DeletedBy)
                .to(super::users::Column::Id)
                .into(),
            Self::Users1 => Entity::belongs_to(super::users::Entity)
                .from(Column::UpdatedBy)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::food_analysis_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FoodAnalysisRequests.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
